version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-net
      - nginx-proxy

networks:
  db-net:
    external: true
  nginx-proxy:
    external: true
